FROM node:20-alpine AS build

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG VITE_APP_TITLE
ARG VITE_BASE_URL
ARG VITE_API_URL
ARG VITE_APP_TENANT_ENABLE
ARG VITE_APP_CAPTCHA_ENABLE
ARG VITE_APP_DEFAULT_LOGIN_TENANT
ARG VITE_APP_DEFAULT_LOGIN_USERNAME
ARG VITE_APP_DEFAULT_LOGIN_PASSWORD

ENV VITE_APP_TITLE=${VITE_APP_TITLE}
ENV VITE_BASE_URL=${VITE_BASE_URL}
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_APP_TENANT_ENABLE=${VITE_APP_TENANT_ENABLE}
ENV VITE_APP_CAPTCHA_ENABLE=${VITE_APP_CAPTCHA_ENABLE}
ENV VITE_APP_DEFAULT_LOGIN_TENANT=${VITE_APP_DEFAULT_LOGIN_TENANT}
ENV VITE_APP_DEFAULT_LOGIN_USERNAME=${VITE_APP_DEFAULT_LOGIN_USERNAME}
ENV VITE_APP_DEFAULT_LOGIN_PASSWORD=${VITE_APP_DEFAULT_LOGIN_PASSWORD}

RUN pnpm build:prod

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist-prod /usr/share/nginx/html

EXPOSE 80
